# Runs at 0/45 by default, skips :15 (and :30) as :15 is the default window for the data import job
jeap.governance.scoring.cron-expression=0 0,45 6-20 * * MON-FRI
jeap.governance.scoring.lock-at-least=PT1M
jeap.governance.scoring.lock-at-most=PT15M
